config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, :on => :member
  end

  root :to => 'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
	<div id="banner">
		<%= image_tag("logo.png") %>
		<%= @page_title || "Pragmatic Bookshelf"%>
	</div>
	<div id="columns">
		<div id="side">
			<% if @cart %>
				<%= hidden_div_if(@cart.line_items.empty?, :id => 'cart') do %>
					<%= render @cart %>
				<% end %>
			<% end %>
			<ul>
				<li><a href="www...">Home</a></li>
				<li><a href="www...">Questions</a></li>
				<li><a href="www...">News</a></li>
				<li><a href="www...">Contact</a>></li>
			</ul>

		    <% if session[:user_id] %>
		    	<br />
		    		<%= link_to 'Orders', orders_path %><br />
		    		<%= link_to 'Products', products_path %><br />
		    		<%= link_to 'Users', users_path %><br />
		    	<br />
		    	<%= button_to 'Logout', logout_path, :method => :delete %>
		    <% end %>
		</div>
		<div id="main">
			<%= yield %>
		</div>
	</div>
</body>
</html>